### ISSUE TITLE
Optimize Build System for faster deployment.

### ISSUE THREAD

**Issue by pwolfert** [Connexions/simulations#396]
Optimize build by not building sims that haven't changed.

Dennis came up with the following method:

Build completion touches a file called `.build_timestamp`.  If when we go to build again, we find files that are newer than that file, we need to build again.  So for each sim directory:
`find rutherford-scattering -type f -newer .build_timestamp`
If this returns a file, we need to build that sim.
After building, we touch the `.build_timestamp` again.

For the cases where we want to build ones that haven't been updated, we'd make a --force flag.

**Comment by pwolfert** [comment]
The modified time for a file is when it was pulled from the repo to the local system.

**Comment by pwolfert** [comment]
Then list which ones were updated so it can be double-checked that the ones intended for updating were indeed updated.

**Comment by dtwilliamson** [comment]
To shortcut the `find` command so it stops as soon as it finds one match:

    find ... -print -quit

That will speed up the process in large file trees.

You can print anything you want instead of the filename:

    find ... -printf 'found!\n' -quit

There are a bunch of specifiers that can be added to output file information a la `stat`.

Unfortunately, `find` only returns non-zero exit codes when there's an error, not when there's no match.

**Comment by pwolfert** [comment]
Oh good point.  Thanks!
