### ISSUE TITLE
My Solar System - Reset button should be labeled Reset, not Rewind

### ISSUE THREAD

**Issue by edwoodward** [Connexions/simulations#94]
The Reset button has hover text of Rewind which makes me think it will move backwards.  It should be labeled Reset.

**Comment by pwolfert** [comment]
I thought people would be afraid to hit a "reset" button because reset normally means resetting all the parameters in the other sims.  Because there's no way to change the parameters after the simulation starts running anyway, I thought "rewind" would be more appropriate because they are just going back to time=0 rather than resetting any of the initial data (position, velocity, number of bodies, etc.) that they had set.  The icon that represents it includes a vertical bar, which is universal to mean going all the way.  What if I changed the label to "Rewind to beginning"?

**Comment by edwoodward** [comment]
Sounds good
