### ISSUE TITLE
My Solar System - Zoom buttons cause odd behavior

### ISSUE THREAD

**Issue by edwoodward** [Connexions/simulations#95]
I was able to cause odd behavior using the zoom buttons. I got the sun out of center on the Sun and planet option, but I couldn't recreate it.  On Sun, Planet and Comet, the comet orbit just gets bigger and bigger regards less of the zoom you select. Should we remove this since it is an enhancement and not part of the original?  If we have time, we can revisit it.

**Comment by pwolfert** [comment]
Are you sure you didn't uncheck "system centered"?  I can't recreate this.  If there is a bug with increasing orbital size, it has nothing to do with the zoom.  Basically, there has to be a transformation between model coordinates and screen coordinates—a model-view-transform—and before I implemented the zooming feature, I had just chosen an arbitrary zoom level that fit the size of the screen in the same proportions as the original.  Changing the zoom level should not affect the simulation.  

I did notice that my scaling of the zoom factor isn't very clean, though, so I will increment and decrement linearly instead of multiplying and dividing.

**Comment by pwolfert** [comment]
This did lead me to find another related bug: https://github.com/Connexions/simulations/commit/53855d88806ddf8e98e92cf5e065f6d4690006b4

It could have been this that caused the odd behavior, and it was caused jointly by a subversive bug in the BodyView and also a bug in the common ModelViewTransform class (`common/math/model-view-transform`).  It was good to find this in any case.

**Comment by edwoodward** [comment]
I was able to recreate the out of center sun by clicking on Run without selecting any Preset.  It only works when the page is first loaded.  Should we prevent users from clicking on Play without a preset?

**Comment by pwolfert** [comment]
We discussed this and decided it was expected behavior.
